config/routes.rb
ZelenyukCom::Application.routes.draw do
  resources :subsites

end

app/models/subsite.rb
class Subsite < ActiveRecord::Base
  attr_accessible :description, :name, :subdomain
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/subsites_controller.rb
class SubsitesController < ApplicationController
  # GET /subsites
  # GET /subsites.json
  def index
    @subsites = Subsite.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subsites }
    end
  end

  # GET /subsites/1
  # GET /subsites/1.json
  def show
    @subsite = Subsite.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subsite }
    end
  end

  # GET /subsites/new
  # GET /subsites/new.json
  def new
    @subsite = Subsite.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subsite }
    end
  end

  # GET /subsites/1/edit
  def edit
    @subsite = Subsite.find(params[:id])
  end

  # POST /subsites
  # POST /subsites.json
  def create
    @subsite = Subsite.new(params[:subsite])

    respond_to do |format|
      if @subsite.save
        format.html { redirect_to @subsite, notice: 'Subsite was successfully created.' }
        format.json { render json: @subsite, status: :created, location: @subsite }
      else
        format.html { render action: "new" }
        format.json { render json: @subsite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subsites/1
  # PUT /subsites/1.json
  def update
    @subsite = Subsite.find(params[:id])

    respond_to do |format|
      if @subsite.update_attributes(params[:subsite])
        format.html { redirect_to @subsite, notice: 'Subsite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subsite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subsites/1
  # DELETE /subsites/1.json
  def destroy
    @subsite = Subsite.find(params[:id])
    @subsite.destroy

    respond_to do |format|
      format.html { redirect_to subsites_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subsites_helper.rb
module SubsitesHelper
end

app/views/layouts/-application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ZelenyukCom</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ZelenyukCom" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">ZelenyukCom</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Zelenyuk Brothers 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/subsites/_form.html.erb
<%= form_for @subsite, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :subdomain, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :subdomain, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                subsites_path, :class => 'btn' %>
  </div>
<% end %>

app/views/subsites/edit.html.erb
<%- model_class = Subsite -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/subsites/index.html.erb
<%- model_class = Subsite -%>
<div class="page-header">
  <h1>Web Pages</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:subdomain) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @subsites.each do |subsite| %>
      <tr>
        <td><%= link_to subsite.id, subsite_path(subsite) %></td>
        <td><%= subsite.name %></td>
        <td><%= subsite.subdomain %></td>
        <td><%= subsite.description %></td>
        <td><%=l subsite.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_subsite_path(subsite), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      subsite_path(subsite),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_subsite_path,
            :class => 'btn btn-primary' %>

app/views/subsites/new.html.erb
<%- model_class = Subsite -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/subsites/show.html.erb
<%- model_class = Subsite -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @subsite.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:subdomain) %>:</strong></dt>
  <dd><%= @subsite.subdomain %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @subsite.description %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              subsites_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_subsite_path(@subsite), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              subsite_path(@subsite),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>